[[redirects]]
from = "/component/:id"
to = "/component/detail.html"
status = 200

[[redirects]]
from = "/component/"
to = "/component/index.html"
status = 200

[[redirects]]
from = "/strain/:id"
to = "/strain/detail.html"
status = 200

[[redirects]]
from = "/strain/"
to = "/strain/index.html"
status = 200

[[redirects]]
from = "/medium/:id"
to = "/medium/detail.html"
status = 200

[[redirects]]
from = "/medium/"
to = "/medium/index.html"
status = 200

[[redirects]]
from = "/taxon/:id"
to = "/taxon/detail.html"
status = 200

[[redirects]]
from = "/taxon/"
to = "/taxon/index.html"
status = 200
