[[redirects]]
from = "/component/*"
to = "/component/detail.html"
status = 301
force = true

[[redirects]]
from = "/component/"
to = "/component/index.html"
status = 200
force = false

[[redirects]]
from = "/strain/*"
to = "/strain/detail.html"
status = 301
force = true

[[redirects]]
from = "/strain/"
to = "/strain/index.html"
status = 200
force = false

[[redirects]]
from = "/medium/*"
to = "/medium/detail.html"
status = 301
force = true

[[redirects]]
from = "/medium/"
to = "/medium/index.html"
status = 200
force = false

[[redirects]]
from = "/taxon/*"
to = "/taxon/detail.html"
status = 301
force = true

[[redirects]]
from = "/taxon/"
to = "/taxon/index.html"
status = 200
force = false
