[[redirects]]
from = "/component/*"
to = "/component/"
status = 200
force = true

[[redirects]]
from = "/strain/*"
to = "/strain/"
status = 200
force = true

[[redirects]]
from = "/medium/*"
to = "/medium/"
status = 200
force = true

[[redirects]]
from = "/taxon/*"
to = "/taxon/"
status = 200
force = true
